### ISSUE TITLE
Add Munchausen syndrome

### ISSUE THREAD

**Issue by icyflame** [icyflame/awesome-social-science#11]
- Sharp Objects by Gillian Flynn

**Comment by vchrombie** [comment]
Hello 
I am interested in this project.

Is this issue assigned?
Can I take this?

**Comment by vchrombie** [comment]
Can you please review my PR #23 and tell me if any changes are required.
Thank You! :)

**Comment by vchrombie** [comment]
Can you please review my PR #24 and tell me if anything is to be changed.
