### ISSUE TITLE
Add The walking corpse syndrome

### ISSUE THREAD

**Issue by Megha66** [icyflame/awesome-social-science#13]
The "walking corpse syndrome" or the "Cotard's Delusion"

People with Cotard’s syndrome believe that they have either died or been mutilated in some improbable manner such as having all of their blood drained or their organs removed. Yet other patients show delusions of immortality.
The condition is most common among schizophrenics and people who’ve suffered head trauma. In one famous case, a young man who hit his head in a motorcycle accident in Scotland left the hospital convinced he was dead from either septicemia or AIDS. Shortly afterward, when his mother took him to South Africa, he came to believe that his soul had been sent to hell.

Reference-http://all-that-is-interesting.com

**Comment by Aexousia** [comment]
Hi Megha,
Please check my addition on this.
Thank you.

**Comment by Megha66** [comment]
Could u tell me what did u do when u made the addition?

**Comment by Aexousia** [comment]
I 'fork'ed it and added my text following the existing one in readme.mt.
Then I 'commit'ed it. It's appearing in the readme, but then 'The Walking
Coarpse' is still being shown as an issue with the others which hasn't been
worked upon yet.

**Comment by Megha66** [comment]
Yes i think no work has yet been done on the walking corpse syndrome.. I
sent a pull request regarding that as well but could'nt see it.. Lets take
some time and see if some response come from the other side.

**Comment by Aexousia** [comment]
Please see if the work is appearing?
To me, it's there on the readme now. Does that appear to you too?
