### ISSUE TITLE
Add Synesthesia

### ISSUE THREAD

**Issue by Megha66** [icyflame/awesome-social-science#14]
Synesthesia
This neurological phenomenon occurs when stimulation of one sense leads to involuntary experiences in another sense or a “union of the senses,” where for example taste and sound are joined together. Some people experience color when they hear sounds or read words and may be able to answer a question like "What color is A?" 
Reference-https://www.alternet.org

**Comment by icyflame** [comment]
AHA! I saw this very recently in True Detective, McConaughey's character talks about this. Thanks for creating this issue!

**Comment by Megha66** [comment]
I m going to send a pull request for this.
