### ISSUE TITLE
Add Clinical lycanthropy

### ISSUE THREAD

**Issue by Megha66** [icyflame/awesome-social-science#15]
Clinical lycanthropy
In this disorder a person believes that he can transform into, has transformed into or is a non-human animal. This is one of the most rarest disorder and most of the times people believe he can transform into a werewolf. 
A person shows symptoms like growling, walking on hands and legs, biting objects or improper eating habits. 
Reference-https://www.trendsnhealth.com

**Comment by Megha66** [comment]
@icyflame i m unable to send pull request ..what should i do???

**Comment by icyflame** [comment]
This does not seem appropriate for this list. Moreover there seems to be some debate about it's existence.

![image](https://user-images.githubusercontent.com/3668034/34192571-d44b99b2-e574-11e7-901d-359b7afce20b.png)

Ref: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1291962/

(Closing #61 for the same reason)
