### ISSUE TITLE
Add Trichotillomania

### ISSUE THREAD

**Issue by Megha66** [icyflame/awesome-social-science#16]
Trichotillomania
 Trichotillomania is a mental disorder where a person feels the urge to pull their own hairs out. Scalp hair, eyebrows, body hairs ad even pubic hairs, they just want to get rid of them. Pulling the hairs out gives them a sense of relief. This disorder becomes dangerous when the person starts eating those hairs thus developing some serious diseases. 
Reference-www.trendsnhealth.com

**Comment by HariMahi** [comment]
can i take this issue
