### ISSUE TITLE
Add Placebo effect

### ISSUE THREAD

**Issue by Megha66** [icyflame/awesome-social-science#17]
Placebo effect
Patients given secretly ineffectual or simulated treatment will perceive that their condition has improved, or that it will improve, because they believe the treatment has benefited or will benefit them.
Reference-www.dailywritingtips.com

**Comment by vchrombie** [comment]
Hello 
I am interested in this project.

Is this issue assigned?
Can I take this?

**Comment by Megha66** [comment]
If u wish to u can work on it 😃

**Comment by vchrombie** [comment]
Thank You! @Megha66

**Comment by Megha66** [comment]
U can search for other things as well 😀

**Comment by Megha66** [comment]
@vchrombie  Are you working on this ?

**Comment by vchrombie** [comment]
Actually my PR #24  is still pending.
I have a prepared the draft for "Plcebo effect".
But I need to get that PR #24 merged.
