### ISSUE TITLE
Add Ganser's Syndrome

### ISSUE THREAD

**Issue by dhruvapte26** [icyflame/awesome-social-science#21]
An extremely rare dissociative disorder, also known as the *balderdash syndrome* as the patient gives absurd answers to trivial questions due to extreme stress.

**Comment by vchrombie** [comment]
Hello 
I am interested in this project.

Is this issue assigned?
Can I take this?

**Comment by HariMahi** [comment]
I'm new to Github, how to contribute to this project, were to include the details about Ganser's Syndorme.

**Comment by rudr4x5h** [comment]
Hello @the-ethan-hunt @vchrombie and @HariMahi. Welcome to the Open Source!

Go through the [contribution guidelines](https://github.com/icyflame/awesome-social-science/blob/master/contributing.md) to know how to contribute to this repository. If you're a total beginner [read more about the open source and how contribution works here](https://opensource.guide/how-to-contribute/) before moving on to contributing your code! All the best 👍

**Comment by HariMahi** [comment]
Hello I made my first PR, so please review it.

**Comment by rudr4x5h** [comment]
@HariMahi I think there's a similar work in progress. Checkout #17. 

Make sure to look the issues and pull requests first to check for the uniqueness of your suggestions. Also, make sure to go through [the introduction to open source](https://opensource.guide/how-to-contribute/) before contributing.
