### ISSUE TITLE
Add Multiple Personality Syndrome

### ISSUE THREAD

**Issue by Budcoderr** [icyflame/awesome-social-science#25]
Multiple Personality Disorder (MPD), or Dissociative Identity Disorder (DID), is the existence in an individual of two or more distinct identities or personalities, each with its own pattern of perceiving and interacting with the environment. At least two of these personalities are considered to routinely take control of the individual's behavior, and is usually a reaction to trauma as a way to help a person avoid bad memories.

R: http://www.psychologistanywhereanytime.com/disorders_psychologist_and_psychologists/psychologist_multiple_personaility_disorder.htm

**Comment by Aexousia** [comment]
I'm doing this.
