### ISSUE TITLE
Add Cotard delusion

### ISSUE THREAD

**Issue by dhruvapte26** [icyflame/awesome-social-science#34]
A very rare mental illness where the patient thinks he/she is dead or is missing some of his/her organs

**Comment by rudr4x5h** [comment]
@the-ethan-hunt make these changes as per the [contribution guidelines](https://github.com/icyflame/awesome-social-science/blob/master/contributing.md) and send a pull request instead!

You've to make the changes to the `readme.md` file, update the ToC and then send a PR here. [Read contribution guidelines properly first](https://github.com/icyflame/awesome-social-science/blob/master/contributing.md).

**Comment by rudr4x5h** [comment]
@the-ethan-hunt yours was a suggestion. My bad 😜
