### ISSUE TITLE
Add Boanthropy

### ISSUE THREAD

**Issue by dhruvapte26** [icyflame/awesome-social-science#39]
The mental illness where the patient thinks he is a bovine

**Comment by HariMahi** [comment]
Can I take this issue

**Comment by icyflame** [comment]
Hey @the-ethan-hunt , thanks for opening this issue. But there seems to be hardly any research or evidence that this is a real delusion at all. I am not ready to add this to the list just yet.

> Boanthropy is such an unusual and uncommon disorder that there is not much research into it, let alone case studies. Even the exact causes have not been nailed down. Boanthropy diagnoses have largely ceased.

[Ref 1](https://psychologyart.wordpress.com/2016/03/23/boanthrophy/)

@HariMahi I am closing #44 for the same reason.
