### ISSUE TITLE
Add Gaming Disorder

### ISSUE THREAD

**Issue by PetalsOnWind** [icyflame/awesome-social-science#71]
WHO plans to add Gaming Disorder in their diagnostic manual, International Classification of Diseases, in its next release in 2018

https://www.psychologytoday.com/blog/your-online-secrets/201712/video-gaming-disorder-is-now-mental-health-condition

**Comment by icyflame** [comment]
I don't think we should jump the gun here. I only want to add syndromes here which have atleast a few years worth of research behind their existence. Thanks for your enthusiasm, nonetheless!  :smile: 

P.S. I will review your other patches soon. :+1:
